"""
Django settings for servico_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Используйте переменную окружения на продакшене, а локально можно использовать дефолт
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-y7ko^_+x)y%ln#83i_qybur4*d+k_b!lbxy+ps!11uybeo#q72')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # ОБЯЗАТЕЛЬНО False на продакшене!

ALLOWED_HOSTS = ['serviko.kz', 'www.serviko.kz', '85.202.193.80'] # Уберите '*' для продакшена

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'adminsortable2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'directory',
    'django_cleanup.apps.CleanupConfig',
]
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'servico_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'servico_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'servico_db',        # Имя вашей базы данных
        'USER': 'servico_user',      # Имя пользователя БД
        'PASSWORD': 'h8$Nq7!Vx2@Rz4%YpK9&Lm3#Tf6^BwQ', # <--- ВАШ СГЕНЕРИРОВАННЫЙ ПАРОЛЬ!
        'HOST': 'localhost',         # БД будет на том же сервере
        'PORT': '',                  # Пустое поле, чтобы использовался порт по умолчанию (5432)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',             # Корневая папка static
    BASE_DIR / 'directory/static',   # Статика из вашего приложения directory
]

STATIC_ROOT = BASE_DIR / 'staticfiles_collected' # Сюда Django будет собирать всю статику для продакшена

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media_files' # Сюда будут загружаться медиафайлы


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    # Заголовок окна входа
    "site_title": "Serviko Admin",

    # Текст в шапке
    "site_header": "Serviko",

    # Логотип в шапке
    "site_logo": None, # Можно указать путь к файлу логотипа в static

    # Текст на экране входа
    "welcome_sign": "Добро пожаловать в панель администрирования Serviko",
    "custom_links": {
        "directory": [{
            "name": "Яндекс.Метрика",
            "url": "https://metrika.yandex.ru/overview?id=104614321", # <-- Ваша ссылка
            "icon": "fas fa-chart-line",
            "new_window": True,
            "permissions": ["auth.view_user"]
        }]
    },
    # Авторские права в подвале
    "copyright": "Serviko Ltd.",

    # Модели, которые нужно скрыть из меню
    "hide_models": [], # Оставил пустым
    "topmenu_links": [
        # Ссылка на главную страницу сайта
        {"name": "Вернуться на сайт", "url": "/", "new_window": True},
    ],
    # Настройка иконок для моделей
    "icons": {
        "auth.User": "fas fa-user",
        "directory.Company": "far fa-building",
        "directory.Category": "fas fa-stream",
        "directory.Service": "fas fa-tools",
        "directory.PortfolioItem": "far fa-image",
        "directory.Certificate": "fas fa-award",
        "directory.Application": "fas fa-envelope", # Иконка для Заявок
        "directory.Review": "fas fa-star",
        "auth.Group": "fas fa-users",
    },

    # Темы оформления
    "theme": "darkly", # Попробуйте "flatly", "cerulean", "litera" и другие
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='uteevmiras64@gmail.com'
# Используйте переменную окружения для пароля почты
EMAIL_HOST_PASSWORD=os.environ.get('EMAIL_HOST_PASSWORD', 'retn lcuw ccfb pyrt')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMIN_EMAIL = 'uteevmiras64@gmail.com' # <-- Замените на ваш email