# Generated by Django 5.2.7 on 2025-10-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='directory.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание для карточки')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для заявок')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес офиса')),
                ('working_hours', models.CharField(max_length=100, verbose_name='График работы (например, Пн-Пт 9:00-18:00)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирована')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна')),
                ('has_fast_response', models.BooleanField(default=False, verbose_name='Быстрый ответ')),
                ('accepts_urgent_orders', models.BooleanField(default=False, verbose_name='Принимает срочные заказы')),
                ('provides_on_site_visits', models.BooleanField(default=False, verbose_name='Осуществляет выезд на объект')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('categories', models.ManyToManyField(to='directory.category', verbose_name='Категории услуг')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created_at'],
            },
        ),
    ]
