# Generated by Django 5.2.7 on 2025-10-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='price_range',
            field=models.CharField(blank=True, choices=[('$', 'Дешево'), ('$$', 'Средне'), ('$$$', 'Дорого'), ('$$$$', 'Очень дорого')], max_length=4, verbose_name='Ценовой диапазон'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Зона обслуживания (город, район)'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.CharField(blank=True, help_text='Например: экспресс-ремонт, эко-материалы, гарантия 5 лет', max_length=255, verbose_name='Теги (через запятую)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='working_hours',
            field=models.CharField(max_length=100, verbose_name='График работы'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Файл (фото или PDF)')),
                ('description', models.CharField(max_length=255, verbose_name='Название/описание сертификата')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='directory.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сертификат или награда',
                'verbose_name_plural': 'Сертификаты и награды',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание работы')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='directory.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения (за час, за м²)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='directory.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
