# Generated by Django 5.2.7 on 2025-10-12 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_company_facebook_url_company_founding_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_companies', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлено в избранное'),
        ),
    ]
