# Generated by Django 5.2.7 on 2025-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
    ]
