# Generated by Django 5.2.7 on 2025-10-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_application_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='desired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата'),
        ),
        migrations.AddField(
            model_name='application',
            name='selected_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.service', verbose_name='Выбранная услуга'),
        ),
    ]
