# Generated by Django 5.2.7 on 2025-10-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_application_desired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telegram_contact',
            field=models.CharField(blank=True, help_text='Username без символа @, например: durov', max_length=100, verbose_name='Telegram контакт'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_contact',
            field=models.CharField(blank=True, help_text='Только цифры, например: 77071234567', max_length=50, verbose_name='WhatsApp контакт'),
        ),
    ]
