# Generated by Django 5.2.7 on 2025-10-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_company_telegram_contact_company_whatsapp_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
