# Generated by Django 5.2.7 on 2025-10-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='price_range',
        ),
    ]
