# Generated by Django 5.2.7 on 2025-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_remove_company_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес офиса'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес офиса'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес офиса'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_area_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зона обслуживания (город, район)'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_area_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зона обслуживания (город, район)'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_area_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зона обслуживания (город, район)'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_description_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание для карточки'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours_en',
            field=models.CharField(max_length=100, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_kk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_ru',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения (за час, за м²)'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_kk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения (за час, за м²)'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения (за час, за м²)'),
        ),
    ]
