# Generated by Django 5.2.7 on 2025-10-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_category_name_en_category_name_kk_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название/описание сертификата'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название/описание сертификата'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название/описание сертификата'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание работы'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание работы'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание работы'),
        ),
    ]
