# Generated by Django 5.2.7 on 2025-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_certificate_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tags_en',
            field=models.CharField(blank=True, help_text='Например: экспресс-ремонт, эко-материалы, гарантия 5 лет', max_length=255, null=True, verbose_name='Теги (через запятую)'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags_kk',
            field=models.CharField(blank=True, help_text='Например: экспресс-ремонт, эко-материалы, гарантия 5 лет', max_length=255, null=True, verbose_name='Теги (через запятую)'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags_ru',
            field=models.CharField(blank=True, help_text='Например: экспресс-ремонт, эко-материалы, гарантия 5 лет', max_length=255, null=True, verbose_name='Теги (через запятую)'),
        ),
    ]
